sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vinay25789/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vinay25789/docker-react npm run test
